### ISSUE TITLE
Проблемы связанные с SSR.

### ISSUE THREAD

**Issue by GTOsss** [ylabio/react-skeleton#15]
- `src/server.js` store создается общий на весь сервер. Нужно переместить его в callback для app.use
- `src/server.js` метод filterRoutes рекурсивно передает routes.children а должен передавать route.children судя по всему.

**Comment by GTOsss** [comment]
Так же есть проблема с initServer. Работает он как нужно, но использование initServer вызывает разное поведение в режиме webpack dev server и в режиме SSR. Первый запрос в initServer просто теряется в режиме webpack dev server. Нужно или научить SSR сервер дожидаться cdm или же научить webpack dev server выполнять initServer.

**Comment by VladimirShestakov** [comment]
Думаю в режиме webpack dev server нет смысла SSR использовать

**Comment by GTOsss** [comment]
Смысла то нет, но как убедиться что SSR работает как надо, если режим webpack dev server работает иначе. Использование webpack dev server нужно для того что бы увидеть как работает приложение, но в данном случае мы видим различая в режиме SSR и dev сервера. Допустим я внес правки в приложение в режиме dev server а потом выясняется что в режиме SSR все работает совсем иначе. По этому нужно добиться схожего поведения, иначе придется после правок тестировать все в режиме SSR.
